# Generated by Django 4.1.9 on 2023-05-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric", models.CharField(db_column="metric", max_length=100)),
                ("category", models.CharField(db_column="category", max_length=100)),
                ("value", models.IntegerField(db_column="value")),
                ("decision", models.IntegerField(db_column="decision")),
            ],
        ),
    ]
