# Generated by Django 4.1.9 on 2023-05-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoFrontApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_column="nome", max_length=100)),
                ("categoria", models.CharField(db_column="categoria", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MetricsValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.IntegerField(db_column="valor")),
                ("tempo", models.IntegerField(db_column="tempo")),
                ("decisao", models.IntegerField(db_column="decisao")),
                (
                    "metrica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangoFrontApp.metrics",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Metric",),
    ]
