# Generated by Django 4.1.9 on 2023-05-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoFrontApp", "0002_metrics_metricsvalues_delete_metric"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsvalues",
            name="cadastrado_por",
            field=models.CharField(
                db_column="cadastrado_por", default="wes", max_length=100
            ),
        ),
    ]
