# Generated by Django 4.1.9 on 2023-05-31 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoFrontApp", "0004_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrics",
            name="project",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="djangoFrontApp.project",
            ),
        ),
        migrations.AlterField(
            model_name="metricsvalues",
            name="cadastrado_por",
            field=models.CharField(
                db_column="cadastrado_por", default="", max_length=100
            ),
        ),
    ]
