# Generated by Django 4.1.9 on 2023-05-31 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoFrontApp", "0005_metrics_project_alter_metricsvalues_cadastrado_por"),
    ]

    operations = [
        migrations.RemoveField(model_name="metrics", name="project",),
        migrations.AddField(
            model_name="metrics",
            name="project_id",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="djangoFrontApp.project",
            ),
        ),
    ]
