# Generated by Django 4.1.9 on 2023-05-31 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoFrontApp", "0008_alter_metrics_project_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metrics", old_name="project_id", new_name="project",
        ),
    ]
