# Generated by Django 4.1.9 on 2023-06-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoFrontApp", "0009_rename_project_id_metrics_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="desc", new_name="descricao",
        ),
        migrations.RenameField(model_name="project", old_name="name", new_name="nome",),
        migrations.RenameField(
            model_name="project", old_name="users", new_name="user",
        ),
    ]
