# Generated by Django 4.1.9 on 2023-06-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoFrontApp", "0011_remove_metrics_project_metrics_projeto"),
    ]

    operations = [
        migrations.RemoveField(model_name="metrics", name="categoria",),
    ]
