# Generated by Django 4.1.9 on 2023-06-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoFrontApp", "0012_remove_metrics_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Origin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=100)),
                ("desc", models.CharField(db_column="desc", max_length=500)),
                (
                    "technology",
                    models.CharField(db_column="technology", max_length=100),
                ),
                ("link", models.CharField(db_column="link", max_length=500)),
                ("emailresp", models.CharField(db_column="emailresp", max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="metrics",
            name="origin",
            field=models.ForeignKey(
                db_column="origin",
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="djangoFrontApp.origin",
            ),
            preserve_default=False,
        ),
    ]
