# Generated by Django 4.1.9 on 2023-06-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoFrontApp", "0013_origin_metrics_origin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="origin", old_name="desc", new_name="descricao",
        ),
        migrations.RenameField(model_name="origin", old_name="name", new_name="nome",),
        migrations.RenameField(
            model_name="origin", old_name="emailresp", new_name="responsavel",
        ),
        migrations.RenameField(
            model_name="origin", old_name="technology", new_name="tecnologia",
        ),
        migrations.RemoveField(model_name="origin", name="link",),
        migrations.AddField(
            model_name="origin",
            name="endpoint",
            field=models.CharField(db_column="endpoint", default=1, max_length=500),
            preserve_default=False,
        ),
    ]
